### ISSUE TITLE
Business Model

### ISSUE THREAD

**Issue by buildrightmatt** [binocarlos/biro#2]
Found this article and found it interesting;
# What is the most profitable business model ever made?

Cory A. Martin
Cory A. Martin, SaaS/IoT Account Executive, Business Growth Expert and Technology Enthusiast
263.9k Views · Most Viewed Writer in Business Models
My personal favorite is the hub and spoke model.

In this model what you do is a have core product (lets say pizza) where you have a low or even negative profit margin. This cheaper but quality product allows you to be able to gain business and sales more easily even when competitors have similar or better products.

Although you don't make much money (or any sometimes) off the hub, what happens is that you offer several 'spokes' which are high profit margin services/products. So lets call this (wings, molten chocolate cakes, 2 liter of Dr. Pepper). So they buy the pizza and then add on the extras so they have a complete product (all in one to place which makes integration and ease of use higher) and you're making high profit margins off the spokes but brought them in for the hub (cheesy delicious hub).

This model allows for multiple options for different types of company. Some will be allergic to wings or hate Dr. Pepper, well great, you can still sell the hub and one spoke (because who doesn't love molten chocolate cakes) and still make a profit and have a satisfied customer.

Some of the fastest growing Saas companies and 'Unicorns' have unleashed this model recently and are having extreme succcess, such as:

Zenefits

Gusto

Tinder (free dating app, spokes include Passport mode, unlimited swipes)

Evernote (I know dying, but still, great idea had they developed better spokes)

So in 2016 I would say that if you're looking to innovate, find areas where the hub and spoke model isn't being used and then USE it to your advantage.

**Comment by binocarlos** [comment]
@buildrightmatt this is very interesting +1

**Comment by buildrightmatt** [comment]
**Why do so many startups fail?**

Russ Ruffino
Russ Ruffino, Business coach and founder of Clients on Demand
7.8k Views
Originally Answered: What are the top reasons why startups fail?
A few years ago, things were pretty tough for me. My company almost failed… the one I put my heart and soul into building.

I almost lost everything I worked so hard to build.

I almost became just another statistic. A statistic tied in with the tens of thousands of others who had failed in their business ventures.

Back in 2013, I had two months of cash left.

I was almost out of money, but I decided to take a risk. I put everything on the line.

I spent $61,423 on the world's top traffic experts.

They couldn't fix my problem.

After burning through tens of thousands of dollars in savings to jumpstart my company, things were NOT clicking like I thought they would.

My business had originally taken off through referrals. They just rolled in. So I thought marketing would be just as easy.

I was wrong.

It's a terrifying feeling when you don't know where your next client is going to come from, especially if you could go bankrupt otherwise.

In those situations, you can tell yourself it's going to somehow be OK, but you don't really know.

But I still had hope. I was learning with each experiment, and I had just enough runway left to try another.

And that was exactly what I needed.

November 2013 was the last time I felt impending doom. After I changed one core strategy, within just 30 days my business skyrocketed from $10,000 to $200,000 per month.

...And that begs the multimillion dollar question:

What changed?

What shift could possibly be so significant that my business grew 20 times over in just one month (and has continued to grow ever since)?

The Crisis

To understand the shift, it's important to understand the $61,423 lesson that led up to it.

The downward spiral started at the beginning of 2013.

I was completing the consulting contracts I had originally gotten through my network, and I was out of referrals.

The first thing I did to bring in new clients was spend months creating a series of articles that walked business owners through improving their online presence. It took me dozens of hours to write and promote these articles.

Each article had a few hundred views. Several people told me they liked them and learned something valuable. However, a few months in, I had to accept the reality that it hadn't generated one sale. Not even one! Painful.

That's when I became desperate.

Foolishly, or perhaps courageously, I decided to hire four of the best social-media-traffic experts in the world.

I was sure that would fix everything.

It didn't.

Instead, it made things worse...much worse.

How much revenue did I generate with that $61,423 investment?

$30,236.

That means for every dollar I spent, I got back about 50 cents.

At first I was frustrated with the consultants. I blamed them. But the frustration shifted inward when I slowly realized that it was completely my fault.

The experts drove a boatload of targeted traffic to my website, but my sales funnel didn't work.

Almost no one bought.

The Turning Point

The turning point came when a mentor looked at all my materials and noticed something that should have been obvious.

He said, "You talk about yourself. You talk about your team. You talk about how great your offering is. Do you know what you don't talk about? The client. What about his needs? What about her problems?"

That's when I realized that I had been a total moron.

I tore down my funnels, all my webpages, and all my ads. I rebuilt everything from scratch around the CLIENT. I stopped talking about myself. I stopped bragging.

Instead, I focused like a laser on my clients' problems and how I could help solve them.

It was basic. It was obvious. Yet this shift was the key that changed everything.

In 30 days, I went from earning 50 cents on every dollar I spent to earning back $15.

My Big Lesson: The Fundamentals Are Fundamental

In a nutshell, what I learned is that you could theoretically have the perfect sales-funnel steps, but if you don't focus on the customer's problem at each step, the funnel will fail.

As a result, what I created for myself was a framework that I now call the Problem-First Approach:

Understand the problem you're solving.
Find the people who want their problem solved NOW.
Build 100 percent of your communication around their problem.
Demonstrate that you have the solution to their problem.
Show them how to reach out to get your help solving their problem.
Do these five steps correctly, and you can begin making sales almost immediately.

As I painfully learned, do just one of these steps poorly, and you don't have a successful business.

Step 1. Deeply understand the problem you are solving and how your product eliminates that problem for your customers.

In order to understand a problem, you need to understand the person with that problem.

In my experience, empathy is the best way to do this. We are all equipped with the amazing ability to feel what others feel. By developing this ability, we can more easily influence others.

I develop empathy for clients by first observing what they actually do in the real world rather than what I think they do (a key step in design thinking). I very closely look at the analytics of what they respond to and don't respond to in the sales process. Next, members of our team interview potential and current clients.

With this information as a foundation, I use my imagination to visualize in vivid detail what it's like to be my client. As a marketer, I ask myself:

What is this person's day like?
What are they concerned about?
What keeps them awake at night?
What are the things they secretly want that they're afraid to share?
What do they think and feel that they wouldn't tell anyone?
What would they hope that someone will give them the power to do?
What do they really want to do? (Not what you think they should do.)
Research shows that when we actively imagine how others might feel in a situation, our empathy increases.

The Takeaway: Don't sell products. Know your client's problems using empathy. Then, sell solutions to those problems.

Step 2. Find the people who want their problem solved NOW.

I now use Twitter and Facebook advertising to target my customers at the exact moment they're looking for solutions to their problem.

On these platforms, I precisely target people by their problems via the pages they follow and show interest in. If someone follows a niche expert who is known for solving a specific problem, it's likely that they have that problem themselves. On the other hand, if they follow a popular musician, they could have any problem.

The Takeaway: Target your customers by the problem you solve for them.

Step 3. Build 100 percent of your communication around the problem.

I demonstrate my deep understanding of the client's problem through my advertisement and landing page. I describe the problem in a rich and powerful way that allows them to visualize the words.

For example, imagine you have a weird tingling in your hand. It's giving you shooting pains in your elbow, and you've never had it before. It's getting worse, and you're not sure what to do. Part of you fears the worst case scenario. Is this a symptom of a fatal condition?

Now, imagine a complete stranger comes up to you and starts to describe your exact pain down to a T. She describes it better than you could. Then, she gives you an idea to try.

Would you trust this person's advice?

I bet you would, purely because she showed that she understood your problem. You'd wonder, "Is this woman reading my mind?"

People care less about fancy titles than they do about solutions to their problems. If you show people that you understand their problem, they will automatically assume that you can solve it.

The Takeaway: Show! Don't tell.

Step 4. Offer ONE piece of free content that demonstrates that you have the solution to their problem.

Next, I create a webinar to provide real value to the prospects I've targeted.

I create only one piece of content because that's all you need when you have great content that solves a problem.

I give away as much of the solution as I can in a single blog post, video, white paper, or webinar. Great free content will get you in front of more people, and it will build a deeper level of trust with them. In a 2012 study of 364 readers, online blog content that gave readers a meaningful learning experience increased trust in the author by 75.6 percent.

Do NOT be afraid to give away your best stuff. Here's why:

There is a huge difference between information and transformation.

Even if you lay out a solution in detail, your audience will still need your product or service to implement it. So dazzle them with the quality of your information. You will always pick up more clients and customers than you would otherwise.

Step 5. Show them how to reach out to get your help solving the problem.

At the end of the webinar, I invite them to have a one-on-one phone call if they feel that working together is a good fit.

Of the people we talk to on the phone, we only extend the opportunity to purchase our program to people who we think are a perfect fit. We only want to work with people if we feel that we can deliver huge value for them. Otherwise, we're doing them a disservice. This means that we say no to 40 percent of the people we talk to.

Take Action

If you take one thing from this article, let it be this...

Entrepreneurship doesn't have to be marked by stress, worry, and overwork.

More than anything else, these are often symptoms of a missing fundamental in your business.

For me, that missing fundamental was not focusing on the customer's problem first.

As a result of adopting the problem-first approach, I have a business that generates nearly $2 million in profit per year and only requires 20 hours of my time per week.

To get started, analyze how well you're doing on the five fundamentals above and do everything humanly possible to make each step work. This may take months of aggravation and things not working, but when it finally "clicks," you'll likely see a huge jump, just like I did.

## 

This Quora answer is a modified version of a guest post  I originally wrote for Inc.

## 

Russ Ruffino is the creator of Clients on Demand. Using his methods, coaches, experts, thought-leaders, and service professionals attract the perfect clients, at the perfect price, anytime they want. To learn more, visit his free webinar.
Updated Jan 20 · View Upvotes
